In [26]:
import torch
import numpy as np

In [5]:
t = torch.Tensor(3, 5, 2)
t

tensor([[[-3.4080e+07,  1.2724e-42],
         [ 0.0000e+00,  0.0000e+00],
         [ 0.0000e+00,  0.0000e+00],
         [ 0.0000e+00,  0.0000e+00],
         [ 0.0000e+00,  0.0000e+00]],

        [[ 0.0000e+00,  0.0000e+00],
         [ 0.0000e+00,  0.0000e+00],
         [ 0.0000e+00,  0.0000e+00],
         [ 0.0000e+00,  0.0000e+00],
         [ 0.0000e+00,  0.0000e+00]],

        [[ 0.0000e+00,  0.0000e+00],
         [ 0.0000e+00,  0.0000e+00],
         [ 0.0000e+00,  0.0000e+00],
         [ 0.0000e+00,  0.0000e+00],
         [ 0.0000e+00,  0.0000e+00]]])

In [7]:
t = torch.empty(3, 5, 2)
t

tensor([[[-3.4081e+07,  1.2724e-42],
         [ 0.0000e+00,  0.0000e+00],
         [ 0.0000e+00,  0.0000e+00],
         [ 0.0000e+00,  0.0000e+00],
         [ 0.0000e+00,  0.0000e+00]],

        [[ 0.0000e+00,  0.0000e+00],
         [ 0.0000e+00,  0.0000e+00],
         [ 0.0000e+00,  0.0000e+00],
         [ 0.0000e+00,  0.0000e+00],
         [ 0.0000e+00,  0.0000e+00]],

        [[ 0.0000e+00,  0.0000e+00],
         [ 0.0000e+00,  0.0000e+00],
         [ 0.0000e+00,  0.0000e+00],
         [ 0.0000e+00,  0.0000e+00],
         [ 0.0000e+00,  0.0000e+00]]])

In [8]:
t.dtype

torch.float32

In [10]:
t = torch.empty(3, 5, 2, dtype=torch.int32)
t

tensor([[[-872283136,        908],
         [         0,          0],
         [         0,          0],
         [         0,          0],
         [         0,          0]],

        [[         0,          0],
         [         0,          0],
         [         0,          0],
         [         0,          0],
         [         0,          0]],

        [[         0,          0],
         [         0,          0],
         [         0,          0],
         [         0,          0],
         [         0,          0]]], dtype=torch.int32)

In [12]:
t = torch.tensor(1)
t

tensor(1)

In [14]:
t = torch.tensor([1])
t

tensor([1])

In [15]:
t.shape

torch.Size([1])

In [16]:
t = torch.tensor([1, 2, 0])
t

tensor([1, 2, 0])

In [17]:
t.shape

torch.Size([3])

In [18]:
t = torch.tensor([[1, 2], [3, 4], [5, 6]])
t

tensor([[1, 2],
        [3, 4],
        [5, 6]])

In [19]:
t.shape

torch.Size([3, 2])

In [20]:
d = [[[1, 2, 3], [4, 5, 6]]]
t = torch.tensor(d, dtype=torch.float32)

In [21]:
t.type()

'torch.FloatTensor'

In [22]:
t.dtype

torch.float32

In [23]:
t.dim()

3

In [24]:
t.size()

torch.Size([1, 2, 3])

In [25]:
t.shape

torch.Size([1, 2, 3])

In [27]:
x = np.array([[1, 2], [3, 4]])
x

array([[1, 2],
       [3, 4]])

In [29]:
t2 = torch.from_numpy(x)
t2

tensor([[1, 2],
        [3, 4]])

In [30]:
t3 = torch.tensor(x, dtype=torch.float32)
t3

tensor([[1., 2.],
        [3., 4.]])

In [31]:
d = t3.numpy()
d

array([[1., 2.],
       [3., 4.]], dtype=float32)

In [32]:
d = t3.numpy().copy()
d

array([[1., 2.],
       [3., 4.]], dtype=float32)

In [34]:
t3.dtype

torch.float32

In [35]:
t4 = t3.float()
t4

tensor([[1., 2.],
        [3., 4.]])