In [1]:
import torch

In [2]:
tz = torch.zeros(2,3)

In [4]:
tz

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [6]:
tz.size()

torch.Size([2, 3])

In [7]:
tz.shape

torch.Size([2, 3])

In [10]:
tz = torch.zeros(2,3, dtype=torch.int32)

In [11]:
tz

tensor([[0, 0, 0],
        [0, 0, 0]], dtype=torch.int32)

In [12]:
tz.size()

torch.Size([2, 3])

In [13]:
tz.shape

torch.Size([2, 3])

In [14]:
t = torch.ones(2,3)

In [15]:
t

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [16]:
torch.eye(3)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [17]:
torch.eye(3, 2)

tensor([[1., 0.],
        [0., 1.],
        [0., 0.]])

In [18]:
torch.eye(3, 2, dtype=torch.int8)

tensor([[1, 0],
        [0, 1],
        [0, 0]], dtype=torch.int8)

In [20]:
t = torch.full((3,4), 5)
t

tensor([[5, 5, 5, 5],
        [5, 5, 5, 5],
        [5, 5, 5, 5]])

In [21]:
torch.arange(7)

tensor([0, 1, 2, 3, 4, 5, 6])

In [22]:
torch.arange(-5, -1)

tensor([-5, -4, -3, -2])

In [23]:
torch.arange(-5, 5, 2)

tensor([-5, -3, -1,  1,  3])

In [24]:
torch.linspace(1, 5, 2)

tensor([1., 5.])

In [25]:
torch.linspace(1, 5, 0)

tensor([])

In [26]:
torch.linspace(1, 5, 1)

tensor([1.])

In [27]:
torch.linspace(1, 5, 10)

tensor([1.0000, 1.4444, 1.8889, 2.3333, 2.7778, 3.2222, 3.6667, 4.1111, 4.5556,
        5.0000])

In [30]:
# от 0 до 1
torch.rand(2, 3)

tensor([[0.1728, 0.3164, 0.0627],
        [0.2246, 0.2460, 0.6766]])

In [31]:
torch.randn(2, 3)

tensor([[-1.1191, -1.7870, -1.1044],
        [-0.7554,  0.3285, -1.0224]])

In [36]:
torch.manual_seed(1)
torch.rand(7, 2)

tensor([[0.7576, 0.2793],
        [0.4031, 0.7347],
        [0.0293, 0.7999],
        [0.3971, 0.7544],
        [0.5695, 0.4388],
        [0.6387, 0.5247],
        [0.6826, 0.3051]])

In [39]:
x = torch.FloatTensor(2, 7)
x

tensor([[-2.8848e-17,  2.0375e-42,  0.0000e+00,  0.0000e+00,  0.0000e+00,
          0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,
          0.0000e+00,  0.0000e+00]])

In [40]:
x.fill_(1)

tensor([[1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1.]])

In [41]:
x

tensor([[1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1.]])

In [42]:
x.fill_(0.3)

tensor([[0.3000, 0.3000, 0.3000, 0.3000, 0.3000, 0.3000, 0.3000],
        [0.3000, 0.3000, 0.3000, 0.3000, 0.3000, 0.3000, 0.3000]])

In [43]:
x.random_(1, 7)

tensor([[2., 1., 1., 4., 3., 5., 1.],
        [4., 3., 5., 4., 1., 5., 3.]])

In [44]:
x

tensor([[2., 1., 1., 4., 3., 5., 1.],
        [4., 3., 5., 4., 1., 5., 3.]])

In [45]:
x.uniform_(0, 1)

tensor([[0.0112, 0.8100, 0.6397, 0.9743, 0.8300, 0.0444, 0.0246],
        [0.2588, 0.9391, 0.4167, 0.7140, 0.2676, 0.9906, 0.2885]])

In [46]:
x.normal_(0, 1)

tensor([[ 2.1130, -0.0040,  1.3800, -1.3505,  0.3455,  0.5046,  1.8213],
        [-0.1814, -0.9515,  0.4057, -1.5164,  0.7322,  2.2820, -1.2080]])

In [50]:
x = torch.FloatTensor(2, 4).zero_()
x

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [65]:
x = torch.arange(27)
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24, 25, 26])

In [66]:
d = x.view(3, 9)
d

tensor([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
        [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23, 24, 25, 26]])

In [67]:
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24, 25, 26])

In [68]:
x[0] = 100
x

tensor([100,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
         14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26])

In [69]:
d

tensor([[100,   1,   2,   3,   4,   5,   6,   7,   8],
        [  9,  10,  11,  12,  13,  14,  15,  16,  17],
        [ 18,  19,  20,  21,  22,  23,  24,  25,  26]])

In [70]:
r = x.reshape(3, 3, 3)
r

tensor([[[100,   1,   2],
         [  3,   4,   5],
         [  6,   7,   8]],

        [[  9,  10,  11],
         [ 12,  13,  14],
         [ 15,  16,  17]],

        [[ 18,  19,  20],
         [ 21,  22,  23],
         [ 24,  25,  26]]])

In [71]:
r[0][0][0] = 0
r

tensor([[[ 0,  1,  2],
         [ 3,  4,  5],
         [ 6,  7,  8]],

        [[ 9, 10, 11],
         [12, 13, 14],
         [15, 16, 17]],

        [[18, 19, 20],
         [21, 22, 23],
         [24, 25, 26]]])

In [72]:
x.resize_(2, 3)

tensor([[0, 1, 2],
        [3, 4, 5]])

In [73]:
x.ravel()

tensor([0, 1, 2, 3, 4, 5])

In [74]:
d

tensor([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
        [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23, 24, 25, 26]])

In [75]:
d.permute(1, 0)

tensor([[ 0,  9, 18],
        [ 1, 10, 19],
        [ 2, 11, 20],
        [ 3, 12, 21],
        [ 4, 13, 22],
        [ 5, 14, 23],
        [ 6, 15, 24],
        [ 7, 16, 25],
        [ 8, 17, 26]])

In [79]:
d.mT

tensor([[ 0,  9, 18],
        [ 1, 10, 19],
        [ 2, 11, 20],
        [ 3, 12, 21],
        [ 4, 13, 22],
        [ 5, 14, 23],
        [ 6, 15, 24],
        [ 7, 16, 25],
        [ 8, 17, 26]])

In [80]:
x_test = torch.arange(32).view(8, 2, 2)
x_test

tensor([[[ 0,  1],
         [ 2,  3]],

        [[ 4,  5],
         [ 6,  7]],

        [[ 8,  9],
         [10, 11]],

        [[12, 13],
         [14, 15]],

        [[16, 17],
         [18, 19]],

        [[20, 21],
         [22, 23]],

        [[24, 25],
         [26, 27]],

        [[28, 29],
         [30, 31]]])

In [81]:
x_test.size()

torch.Size([8, 2, 2])

In [82]:
x_test.shape

torch.Size([8, 2, 2])

In [84]:
x_test4 = torch.unsqueeze(x_test, dim=0)
x_test4

tensor([[[[ 0,  1],
          [ 2,  3]],

         [[ 4,  5],
          [ 6,  7]],

         [[ 8,  9],
          [10, 11]],

         [[12, 13],
          [14, 15]],

         [[16, 17],
          [18, 19]],

         [[20, 21],
          [22, 23]],

         [[24, 25],
          [26, 27]],

         [[28, 29],
          [30, 31]]]])

In [85]:
r = x_test.unsqueeze(0)
r

tensor([[[[ 0,  1],
          [ 2,  3]],

         [[ 4,  5],
          [ 6,  7]],

         [[ 8,  9],
          [10, 11]],

         [[12, 13],
          [14, 15]],

         [[16, 17],
          [18, 19]],

         [[20, 21],
          [22, 23]],

         [[24, 25],
          [26, 27]],

         [[28, 29],
          [30, 31]]]])

In [86]:
x_test.unsqueeze_(0)

tensor([[[[ 0,  1],
          [ 2,  3]],

         [[ 4,  5],
          [ 6,  7]],

         [[ 8,  9],
          [10, 11]],

         [[12, 13],
          [14, 15]],

         [[16, 17],
          [18, 19]],

         [[20, 21],
          [22, 23]],

         [[24, 25],
          [26, 27]],

         [[28, 29],
          [30, 31]]]])

In [87]:
x_test.size()

torch.Size([1, 8, 2, 2])

In [89]:
b = torch.unsqueeze(x_test, dim=-1)
b.size()

torch.Size([1, 8, 2, 2, 1])

In [91]:
c = torch.squeeze(b)
c

tensor([[[ 0,  1],
         [ 2,  3]],

        [[ 4,  5],
         [ 6,  7]],

        [[ 8,  9],
         [10, 11]],

        [[12, 13],
         [14, 15]],

        [[16, 17],
         [18, 19]],

        [[20, 21],
         [22, 23]],

        [[24, 25],
         [26, 27]],

        [[28, 29],
         [30, 31]]])

In [92]:
c.size()

torch.Size([8, 2, 2])