In [1]:
import torch

In [2]:
a = torch.arange(12)
a

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [3]:
a[2]

tensor(2)

In [4]:
a[2].item()

2

In [5]:
a[-1]

tensor(11)

In [6]:
a[-2]

tensor(10)

In [7]:
a[0] = 100

In [8]:
a[0].item()

100

In [10]:
b = a[2:4]
b

tensor([2, 3])

In [12]:
b[0] = 100
b

tensor([100,   3])

In [13]:
a

tensor([100,   1, 100,   3,   4,   5,   6,   7,   8,   9,  10,  11])

In [14]:
a[3:]

tensor([ 3,  4,  5,  6,  7,  8,  9, 10, 11])

In [15]:
a[:5]

tensor([100,   1, 100,   3,   4])

In [16]:
a[-5:-1]

tensor([ 7,  8,  9, 10])

In [17]:
a[1:6:2]

tensor([1, 3, 5])

In [18]:
a[::2]

tensor([100, 100,   4,   6,   8,  10])

In [19]:
a[:4] = torch.IntTensor([-1,-2,-3,-4])
a

tensor([-1, -2, -3, -4,  4,  5,  6,  7,  8,  9, 10, 11])

In [22]:
x = torch.IntTensor([(1, 2, 3),(4, 5, 6),(7, 8, 9)])
x

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]], dtype=torch.int32)

In [23]:
x.shape

torch.Size([3, 3])

In [24]:
x.size()

torch.Size([3, 3])

In [25]:
x[1, 1]

tensor(5, dtype=torch.int32)

In [26]:
x[0]

tensor([1, 2, 3], dtype=torch.int32)

In [28]:
x[:,0]

tensor([1, 4, 7], dtype=torch.int32)

In [30]:
a = torch.arange(1,82).view(3,3,3,3)
a[1,2,0,1]

tensor(47)

In [31]:
a[:, 1, :, :]

tensor([[[10, 11, 12],
         [13, 14, 15],
         [16, 17, 18]],

        [[37, 38, 39],
         [40, 41, 42],
         [43, 44, 45]],

        [[64, 65, 66],
         [67, 68, 69],
         [70, 71, 72]]])

In [33]:
a

tensor([[[[ 1,  2,  3],
          [ 4,  5,  6],
          [ 7,  8,  9]],

         [[10, 11, 12],
          [13, 14, 15],
          [16, 17, 18]],

         [[19, 20, 21],
          [22, 23, 24],
          [25, 26, 27]]],


        [[[28, 29, 30],
          [31, 32, 33],
          [34, 35, 36]],

         [[37, 38, 39],
          [40, 41, 42],
          [43, 44, 45]],

         [[46, 47, 48],
          [49, 50, 51],
          [52, 53, 54]]],


        [[[55, 56, 57],
          [58, 59, 60],
          [61, 62, 63]],

         [[64, 65, 66],
          [67, 68, 69],
          [70, 71, 72]],

         [[73, 74, 75],
          [76, 77, 78],
          [79, 80, 81]]]])

In [34]:
a[..., 1, 1]

tensor([[ 5, 14, 23],
        [32, 41, 50],
        [59, 68, 77]])

In [36]:
a[1]

tensor([[[28, 29, 30],
         [31, 32, 33],
         [34, 35, 36]],

        [[37, 38, 39],
         [40, 41, 42],
         [43, 44, 45]],

        [[46, 47, 48],
         [49, 50, 51],
         [52, 53, 54]]])

In [40]:
a = torch.arange(1, 9)
a

tensor([1, 2, 3, 4, 5, 6, 7, 8])

In [41]:
a[0]

tensor(1)

In [42]:
a[[0]]

tensor([1])

In [43]:
b = a[[0]]
b.shape

torch.Size([1])

In [44]:
b[0] = 10000

In [45]:
b

tensor([10000])

In [46]:
a

tensor([1, 2, 3, 4, 5, 6, 7, 8])

In [47]:
b = a[[0, 1, 7, 5]]
b

tensor([1, 2, 8, 6])

In [51]:
b = a[[0, 0, 1, 1, -1, -1]]
b

tensor([1, 1, 2, 2, 8, 8])

In [54]:
# можно использовать и BoolTensor
indx = torch.IntTensor([0, 0, 1, 1, -1, -1])
indx

tensor([ 0,  0,  1,  1, -1, -1], dtype=torch.int32)

In [55]:
b = a[indx]
b

tensor([1, 1, 2, 2, 8, 8])

In [56]:
a[a > 5]

tensor([6, 7, 8])