In [1]:
import torch

In [5]:
a = torch.FloatTensor([1, 2, 3])
a

tensor([1., 2., 3.])

In [6]:
a - 3

tensor([-2., -1.,  0.])

In [7]:
-a

tensor([-1., -2., -3.])

In [8]:
a + 2

tensor([3., 4., 5.])

In [9]:
a * 5

tensor([ 5., 10., 15.])

In [10]:
a ** 3

tensor([ 1.,  8., 27.])

In [11]:
a / 3

tensor([0.3333, 0.6667, 1.0000])

In [12]:
a // 3

tensor([0., 0., 1.])

In [13]:
a % 3

tensor([1., 2., 0.])

In [14]:
b = torch.IntTensor([3, 4, 5])
b

tensor([3, 4, 5], dtype=torch.int32)

In [16]:
c = a + b
c.dtype

torch.float32

In [17]:
b ** a

tensor([  3.,  16., 125.])

In [34]:
a = torch.arange(1, 19, dtype=torch.float32).view(3,3,2)
b = torch.ones(3, 2, dtype=torch.float32)

In [35]:
a // b

tensor([[[ 1.,  2.],
         [ 3.,  4.],
         [ 5.,  6.]],

        [[ 7.,  8.],
         [ 9., 10.],
         [11., 12.]],

        [[13., 14.],
         [15., 16.],
         [17., 18.]]])

In [36]:
a + b

tensor([[[ 2.,  3.],
         [ 4.,  5.],
         [ 6.,  7.]],

        [[ 8.,  9.],
         [10., 11.],
         [12., 13.]],

        [[14., 15.],
         [16., 17.],
         [18., 19.]]])

In [37]:
a += b

In [38]:
a

tensor([[[ 2.,  3.],
         [ 4.,  5.],
         [ 6.,  7.]],

        [[ 8.,  9.],
         [10., 11.],
         [12., 13.]],

        [[14., 15.],
         [16., 17.],
         [18., 19.]]])