In [1]:
import torch

In [4]:
a = torch.FloatTensor([1, 2, 3, 4, 5])
a

tensor([1., 2., 3., 4., 5.])

In [7]:
b = torch.arange(1, 9, dtype=torch.float32)
b

tensor([1., 2., 3., 4., 5., 6., 7., 8.])

In [8]:
a.sum()

tensor(15.)

In [9]:
a.sum().item()

15.0

In [10]:
a.mean(), a.max(), a.min()

(tensor(3.), tensor(5.), tensor(1.))

In [11]:
b = b.view(2, 4)
b

tensor([[1., 2., 3., 4.],
        [5., 6., 7., 8.]])

In [12]:
b.sum()

tensor(36.)

In [13]:
b.sum(dim=0)

tensor([ 6.,  8., 10., 12.])

In [14]:
b.sum(dim=1)

tensor([10., 26.])

In [17]:
b.max(dim=1).values

tensor([4., 8.])

In [18]:
b.amax(dim=1)

tensor([4., 8.])

In [20]:
a = torch.IntTensor([1, 2, 3, 4, 5])
a

tensor([1, 2, 3, 4, 5], dtype=torch.int32)

In [21]:
torch.abs(a)

tensor([1, 2, 3, 4, 5], dtype=torch.int32)

In [22]:
torch.amax(a)

tensor(5, dtype=torch.int32)

In [23]:
torch.log(a)

tensor([0.0000, 0.6931, 1.0986, 1.3863, 1.6094])

In [24]:
torch.round(a)

tensor([1, 2, 3, 4, 5], dtype=torch.int32)

In [26]:
a = a.float()
a

tensor([1., 2., 3., 4., 5.])

In [27]:
x = torch.FloatTensor([1,2,3,4,5])
y = torch.FloatTensor([6,7,8,9,10])

In [29]:
x.var()

tensor(2.5000)

In [30]:
y.std()

tensor(1.5811)

In [31]:
xy = torch.vstack([x,y])
xy

tensor([[ 1.,  2.,  3.,  4.,  5.],
        [ 6.,  7.,  8.,  9., 10.]])

In [32]:
torch.corrcoef(xy)

tensor([[1., 1.],
        [1., 1.]])

In [33]:
torch.cov(xy)

tensor([[2.5000, 2.5000],
        [2.5000, 2.5000]])